#include <vector>
#include <string>

std::vector<std::string> DATA = {
    "NON_PEN_GOALS",
    "NON_PEN_XG",
    "TOTAL_SHOTS",
    "ASSISTS",
    "XA",
    "NON_PEN_XG+XA",
    "SHOT_CREATIONS",
    "PASSES_ATTEMPTED",
    "PASS_COMPLETION_PERCENTAGE",
    "PROGRESSIVE_PASSES",
    "PROGRESSIVE CARRIES",
    "DRIBBLES_COMPLETED",
    "TOUCHES_IN_AREA",
    "PROGRESSIVE_PASSES_RECIEVED",
    "PRESSURES",
    "TACKLES",
    "INTERCEPTIONS",
    "BLOCKS",
    "CLEARANCES",
    "AERIAL_DUELS_WON",
    "POST_SHOT_XG-CONCEDED",
    "GOALS_CONCEDED",
    "SAVE_PERCENTAGE",
    "POST_SHOT_XG_PER_SHOT_ON_TARGET",
    "PENALTY_SAVE_PERCENTAGE",
    "CLEAN_SHEET_PERCENTAGE",
    "TOUCHES",
    "LAUNCH_PERCENTAGE",
    "GOAL_KICKS",
    "AVG_GOAL_KICK_DISTANCE",
    "CROSSES_STOPPED_PERCENTAGE",
    "DEFENSIVE_ACTIONS_OUTSIDE_AREA",
    "AVG_DISTANCE_OF_DEFENSIVE_ACTIONS"
};

std::vector<std::string> FW_DATA = {
    "NON_PEN_GOALS",
    "NON_PEN_XG",
    "TOTAL_SHOTS",
    "ASSISTS",
    "XA",
    "NON_PEN_XG+XA",
    "SHOT_CREATIONS"
};
std::vector<std::string> MF_DATA = {
    "PASSES_ATTEMPTED",
    "PASS_COMPLETION_PERCENTAGE",
    "PROGRESSIVE_PASSES",
    "PROGRESSIVE CARRIES",
    "DRIBBLES_COMPLETED",
    "TOUCHES_IN_AREA",
    "PROGRESSIVE_PASSES_RECIEVED"
};
std::vector<std::string> DF_DATA = {
    "PRESSURES",
    "TACKLES",
    "INTERCEPTIONS",
    "BLOCKS",
    "CLEARANCES",
    "AERIAL_DUELS_WON"
};
std::vector<std::string> GK_DATA = {
    "POST_SHOT_XG-CONCEDED",
    "GOALS_CONCEDED",
    "SAVE_PERCENTAGE",
    "POST_SHOT_XG_PER_SHOT_ON_TARGET",
    "PENALTY_SAVE_PERCENTAGE",
    "CLEAN_SHEET_PERCENTAGE",
    "TOUCHES",
    "LAUNCH_PERCENTAGE",
    "GOAL_KICKS",
    "AVG_GOAL_KICK_DISTANCE",
    "CROSSES_STOPPED_PERCENTAGE",
    "DEFENSIVE_ACTIONS_OUTSIDE_AREA",
    "AVG_DISTANCE_OF_DEFENSIVE_ACTIONS"
};
